version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  service:
    build: ./service
    container_name: lana
    restart: on-failure
    environment:
      POSTGRES_DB_URL: jdbc:postgresql://postgres:5432/lana
      TG_TOKEN: 6526296723:AAFPI60dFGA4AKhESy52efFGdvJ5o7b1m6A
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgis/postgis:15-3.3-alpine
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: lana
      POSTGRES_PASSWORD: 123
    ports:
      - 5433:5432
    networks:
      - app-network
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 10
