server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"
  metrics:
    tags:
      service: bot
  prometheus:
    metrics:
      export:
        enabled: true

telegram:
  bot:
    token: ${TG_TOKEN}
    name: Lana

rest:
  core:
    url: http://localhost:8080