management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"
  metrics:
    tags:
      service: core
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5433/core}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
